### ISSUE TITLE
cannot dump configuration

### ISSUE THREAD

**Issue by garak** [BeSimple/BeSimpleSsoAuthBundle#94] opened 2016-09-30 11:44 UTC
After installing and configuring this bundle, I tried to execute `bin/console debug:config be_simple_sso_auth` and got the following error:

```
[LogicException]                                                                                 
The extension with alias "be_simple_sso_auth" does not have its getConfiguration() method setup
```

**Comment by acidjames** [comment] 2017-10-24 12:37
Hi @garak 

i don't have any debug command called "configuration", neither in sf2, nor sf3, what's that ?

**Comment by garak** [comment] 2017-10-24 12:40
My bad, the command is `debug:config`, not `debug:configuration` (I edited my original message)

**Comment by acidjames** [comment] 2017-10-24 12:46
haha i guess i'm blind because i could've guessed that...

well apparently, the command now works, i can't reproduce the bug so i'll close this

**Closed by acidjames** 2017-10-24 12:46 UTC
